//! **LLM Client** abstraction — provider-agnostic interface for language models.
//!
//! Defines the [`LlmClient`] trait and associated types for conversation
//! messages, tool calls, and request/response structures.

use crate::agent::tool::ToolSpec;
use serde_json::Value;
use std::sync::Arc;

/// Role of a message in the conversation.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Role {
    /// System prompt / instruction.
    System,
    /// End-user message.
    User,
    /// Assistant (LLM) response.
    Assistant,
    /// Result of a tool call.
    Tool,
}

impl Role {
    /// Serialized role name used in LLM APIs.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::Tool => "tool",
        }
    }
}

/// A tool call request generated by the LLM.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call.
    pub id: String,
    /// Name of the tool to invoke.
    pub name: String,
    /// JSON arguments for the tool.
    pub arguments: Value,
}

/// A single message in the conversation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ChatMessage {
    /// Role of the message author.
    pub role: Role,
    /// Text content. `None` for assistant messages with only tool calls.
    pub content: Option<String>,
    /// Reasoning content from reasoning models (e.g. DeepSeek-R1, mimo-v2.5).
    /// This is the model's "thinking process" shown separately from the final answer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,
    /// Tool calls made by the assistant (assistant messages only).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Tool call ID this message is responding to (tool messages only).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Optional tag for synthetic / loop-continuation messages.
    /// When set to `"loop_continuation"` the message is excluded from
    /// active-turn protection (see [`ScrollStrategy`](crate::agent::memory::ScrollStrategy)).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub qwenpaw_tag: Option<String>,
}

impl ChatMessage {
    /// Returns `true` if this is a synthetic loop-continuation message.
    #[must_use]
    pub fn is_synthetic(&self) -> bool {
        self.qwenpaw_tag.as_deref() == Some("loop_continuation")
    }
    /// Create a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: Some(content.into()),
            reasoning_content: None,
            tool_calls: None,
            tool_call_id: None,
            qwenpaw_tag: None,
        }
    }

    /// Create a user message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: Some(content.into()),
            reasoning_content: None,
            tool_calls: None,
            tool_call_id: None,
            qwenpaw_tag: None,
        }
    }

    /// Create a synthetic loop-continuation user message.
    ///
    /// These messages are excluded from active-turn protection.
    pub fn synthetic_user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: Some(content.into()),
            reasoning_content: None,
            tool_calls: None,
            tool_call_id: None,
            qwenpaw_tag: Some("loop_continuation".into()),
        }
    }

    /// Create an assistant message with text content.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: Some(content.into()),
            reasoning_content: None,
            tool_calls: None,
            tool_call_id: None,
            qwenpaw_tag: None,
        }
    }

    /// Create an assistant message containing tool calls (no text).
    #[must_use]
    pub fn with_tool_calls(tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: Role::Assistant,
            content: None,
            reasoning_content: None,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
            qwenpaw_tag: None,
        }
    }

    /// Create a tool result message.
    pub fn tool_result(tool_call_id: &str, content: &Value) -> Self {
        Self {
            role: Role::Tool,
            content: Some(content.to_string()),
            reasoning_content: None,
            tool_calls: None,
            tool_call_id: Some(tool_call_id.to_string()),
            qwenpaw_tag: None,
        }
    }
}

/// Request sent to an LLM.
#[derive(Debug, Clone)]
pub struct ChatRequest {
    /// Conversation messages.
    pub messages: Vec<ChatMessage>,
    /// Tool specifications for function calling (optional).
    pub tools: Option<Vec<ToolSpec>>,
    /// Sampling temperature.
    pub temperature: Option<f32>,
    /// Maximum tokens in the response.
    pub max_tokens: Option<u32>,
}

/// Token usage statistics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Usage {
    /// Tokens in the prompt.
    pub prompt_tokens: u32,
    /// Tokens in the completion.
    pub completion_tokens: u32,
}

/// Response from an LLM.
#[derive(Debug, Clone)]
pub struct ChatResponse {
    /// The assistant's response message.
    pub message: ChatMessage,
    /// Token usage statistics (if available).
    pub usage: Option<Usage>,
}

/// Error from an LLM client.
#[derive(Debug, thiserror::Error)]
pub enum LlmError {
    /// The LLM request failed (network, auth, rate limit, etc.).
    #[error("LLM request failed: {0}")]
    Request(String),
    /// Failed to parse the LLM response.
    #[error("LLM response parse error: {0}")]
    Parse(String),
    /// The LLM returned an explicit error.
    #[error("LLM API error: {0}")]
    Api(String),
    /// Internal error.
    #[error(transparent)]
    Internal(#[from] Box<dyn std::error::Error + Send + Sync>),
}

impl Clone for LlmError {
    fn clone(&self) -> Self {
        match self {
            Self::Request(s) => Self::Request(s.clone()),
            Self::Parse(s) => Self::Parse(s.clone()),
            Self::Api(s) => Self::Api(s.clone()),
            Self::Internal(e) => Self::Internal(e.to_string().into()),
        }
    }
}

/// A single chunk produced during a streaming agent execution.
///
/// Stream chunks are emitted by [`Agent::execute_stream`](crate::agent::runtime::Agent::execute_stream)
/// and represent the agent's progress at the token/tool level.
#[derive(Debug, Clone)]
pub enum StreamChunk {
    /// A text token from the LLM.
    Token(String),
    /// Reasoning content from a reasoning model (e.g. DeepSeek-R1, mimo-v2.5).
    /// This is the model's "thinking process" emitted separately from final tokens.
    Reasoning(String),
    /// A tool call has started.
    ToolCallStart {
        /// Tool call ID.
        id: String,
        /// Tool name.
        name: String,
    },
    /// A tool call has completed.
    ToolCallEnd {
        /// Tool call ID.
        id: String,
    },
    /// A delta of tool call arguments from the LLM streaming API.
    /// Contains the fully accumulated arguments JSON for a tool call.
    ToolCallArguments {
        /// Tool call ID.
        id: String,
        /// Complete parsed JSON arguments.
        arguments: serde_json::Value,
    },
    /// The agent execution finished successfully.
    Done,
    /// The agent execution encountered an error.
    Error(String),
}

/// Abstract LLM client.
///
/// Implement this trait for any LLM provider (e.g. `OpenAI`, `Anthropic`).
#[async_trait::async_trait]
pub trait LlmClient: Send + Sync {
    /// Send a chat request and receive a response.
    async fn chat(&self, request: ChatRequest) -> Result<ChatResponse, LlmError>;

    /// Send a chat request and receive a stream of response chunks.
    ///
    /// The default implementation returns an error indicating streaming
    /// is not supported by this client.  Override this to provide
    /// token-level streaming from your LLM provider.
    ///
    /// Each `Receiver<StreamChunk>` contains the full sequence of
    /// tokens, tool call boundaries, and a terminal `StreamChunk::Done`
    /// or `StreamChunk::Error`.
    async fn chat_stream(
        &self,
        _request: ChatRequest,
    ) -> Result<tokio::sync::mpsc::Receiver<StreamChunk>, LlmError> {
        Err(LlmError::Request("streaming not supported".into()))
    }
}

#[async_trait::async_trait]
impl LlmClient for Arc<dyn LlmClient> {
    async fn chat(&self, request: ChatRequest) -> Result<ChatResponse, LlmError> {
        self.as_ref().chat(request).await
    }

    async fn chat_stream(
        &self,
        request: ChatRequest,
    ) -> Result<tokio::sync::mpsc::Receiver<StreamChunk>, LlmError> {
        self.as_ref().chat_stream(request).await
    }
}
